---
- name: Test git role
  hosts: localhost
  connection: local
  gather_facts: true
  become: false
  roles:
    - git
  pre_tasks:
    - name: Set HOME environment variable for test user
      ansible.builtin.set_fact:
        ansible_env:
          HOME: "{{ ansible_env.HOME }}"
          PATH: "/usr/local/bin:/usr/bin:/bin"

    - name: Set test mode variable
      ansible.builtin.set_fact:
        molecule_test: true

    - name: Set test user home
      ansible.builtin.set_fact:
        test_user_home: "{{ ansible_env.HOME }}"
