---
dependency:
  name: galaxy
  enabled: false
driver:
  name: default
  options:
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_connection: local
  config_options:
    defaults:
      callbacks_enabled: profile_tasks,timer
      roles_path: ../../..
    ssh_connection:
      pipelining: false
scenario:
  test_sequence:
    - converge
    - idempotence
    - verify
verifier:
  name: ansible
