---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    collections-file: collections.yml
driver:
  name: default
  options:
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: localhost
provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost:
        ansible_connection: local
  config_options:
    defaults:
      callbacks_enabled: profile_tasks,timer,yaml
    ssh_connection:
      pipelining: false
scenario:
  test_sequence:
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
verifier:
  name: ansible
