---
- name: Test common role
  hosts: localhost
  gather_facts: true
  become: false
  roles:
    - common
  pre_tasks:
    - name: Set HOME environment variable for test user
      ansible.builtin.set_fact:
        ansible_env:
          HOME: "{{ ansible_env.HOME }}"
          PATH: "/usr/local/bin:/usr/bin:/bin"
